import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Navigator from '../components/navigator'
import Header from '../components/header'
import Card from '../components/card'
import Box from '../components/box'
import Hero from '../components/hero'
import Footer from '../components/footer'
import Empower from '../components/empower'
import FlipContainer from '../components/flipCardContainer'

const Home: NextPage = () => {
  const a = [
    'Specialist Disability Accomodation',
    'Supported Independent Living',
    'Day Centre',
    'Support Coordination',
  ];
  const b = ['My self', 'Other'];

  const c = ['Victoria', 'Qld'];
  const menuItems = ['Home', 'About Us' , "Services" ,"Newsroom" ,"Work With Us" ,"Contact Us"]
  const card = " Up front and open costs. We're here to help you and to enjoy some time with you"
  const description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.container}>
    {/* <Navigator
        background="#F7F7F7"
        heading="How Can We Help ? "
        headingColor="#BB060A"
        dropdownTitle={['I would like information on', 'For', 'Where ? ']}
        buttonColor="#BB060A"
        dataA={a}
        dataB={b}
        dataC={c}
    /> */}
    
    
    {/* <Card background='#F7F7F7' logo="../noun-magnifier.svg" content='Free Activities & Meals' contentColor="#2B2D42" hoverContent={card} hoverContentColor={'#F7F7F7'}/> */}
    {/* <Box background='#F7F7F7' hasLogo={true} location="Queensland" description={description} picture={"../old-couple.png"} textColor='#2B2D42'/>  */}
    <div style={{ display : 'flex' , alignItems : 'center' ,width : '100vw' , flexDirection : 'column'}}>
    <Header menuList={menuItems} />
    <Hero picture='../homepageHero.png' quote='Empowering People With Choices'/>
    <div className={styles.navigator} style={{ margin : '0 auto'}}>
    <Navigator
        background="#F7F7F7"
        heading="How Can We Help ? "
        headingColor="#BB060A"
        dropdownTitle={['I would like information on', 'For', 'Where ? ']}
        buttonColor="#BB060A"
        dataA={a}
        dataB={b}
        dataC={c}
    />
    </div>
    <div className={styles.empty}>
    </div>
    <Empower/>
    <FlipContainer box={false}/>
    <FlipContainer box={true}/>
    <FlipContainer box={true}/>


    <Footer/>
    </div>
    </div>
    </>

  )
}

export default Home
