import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navigator from "../components/navigator";
import Header from "../components/header";
import Hero from "../components/hero";
import Footer from "../components/footer";
import Empower from "../components/empower";
import FlipContainer from "../components/flipCardContainer";

const Home: NextPage = () => {
  const a = [
    "Specialist Disability Accomodation",
    "Supported Independent Living",
    "Day Centre",
    "Support Coordination",
  ];
  const b = ["My self", "Other"];

  const c = ["Victoria", "Qld"];
  const menuItems = [
    "Home",
    "About Us",
    "Services",
    "Newsroom",
    "Work With Us",
    "Contact Us",
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            width: "100vw",
            flexDirection: "column",
          }}
        >
          <Header menuList={menuItems} />
          <Hero
            picture="../homepageHero.png"
            quote="Empowering People With Choices"
          />
          <div className={styles.navigator} style={{ margin: "0 auto" }}>
            <Navigator
              background="#F7F7F7"
              heading="How Can We Help ? "
              headingColor="#BB060A"
              dropdownTitle={["I would like information on", "For", "Where ? "]}
              buttonColor="#BB060A"
              dataA={a}
              dataB={b}
              dataC={c}
            />
          </div>
          <div className={styles.empty}></div>
          <Empower />
          <FlipContainer box={false} />
          <FlipContainer box={true} />
          <FlipContainer box={true} />
          <Footer />
        </div>
      </div>
    </>
  );
};

export default Home;
